# Flow WM K=4 with strong regularization (tighter gradient clipping)
# Testing stronger regularization for world model via gradient clipping
_target_: flow_mbpo_pwm.algorithms.pwm.PWM
_recursive_: False
actor_config:
  _target_: flow_mbpo_pwm.models.actor.ActorStochasticMLP
  units: [400, 200, 100]
  activation_class: nn.Mish
  init_gain: 1.0
  init_logstd: -1.0
  min_logstd: -1.427
critic_config:
  _target_: flow_mbpo_pwm.models.critic.CriticMLP
  units: [400, 200]
  activation_class: nn.Mish
world_model_config:
  _target_: flow_mbpo_pwm.models.flow_world_model.FlowWorldModel
  units: [512, 512]
  encoder_units: [256]
  num_bins: 101
  vmin: -10.0
  vmax: 10.0
  task_dim: 0
  multitask: False
  action_dims: null
  tasks: null
  encoder:
    last_layer: normedlinear
    last_layer_kwargs:
      act:
        _target_: flow_mbpo_pwm.models.mlp.SimNorm
        simnorm_dim: 8
  dynamics:
    last_layer: normedlinear
    last_layer_kwargs:
      act:
        _target_: flow_mbpo_pwm.models.mlp.SimNorm
        simnorm_dim: 8
  reward:
    last_layer: linear
    last_layer_kwargs: {}
num_critics: 3
latent_dim: 512
actor_lr: 5e-4
critic_lr: 5e-4
model_lr: 3e-4
lr_schedule: linear
obs_rms: False
rew_rms: False
ret_rms: True
critic_iterations: 8
critic_batches: 4
critic_method: td-lambda
lam: 0.95
gamma: 0.99
max_epochs: 15_000
horizon: ${horizon}
actor_grad_norm: 0.5               # ABLATION: Tighter gradient clip (vs 1.0 base)
critic_grad_norm: 50.0             # ABLATION: Tighter gradient clip (vs 100.0 base)
wm_batch_size: 256
wm_iterations: 8
wm_grad_norm: 10.0                 # ABLATION: Tighter gradient clip (vs 20.0 base)
wm_buffer_size: 1_000_000
detach: True
save_interval: 500
device: ${general.device}

use_flow_dynamics: true
flow_integrator: heun
flow_substeps: 4
flow_tau_sampling: uniform
